app = "quatwin-tai-xiu"
primary_region = "sin"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  JWT_SECRET = "quatwin_secret_key_2024"

[[mounts]]
  source = "database_volume"
  destination = "/app/database"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
